# Generated by Django 2.0 on 2020-04-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='countrybirth',
            new_name='country_birth',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='datebirth',
            new_name='date_birth',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='datedeath',
            new_name='date_death',
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='yearfoundation',
            new_name='year_foundation',
        ),
    ]
